-- AlterTable
ALTER TABLE "docentes" ADD COLUMN IF NOT EXISTS "sede" TEXT;
ALTER TABLE "docentes" ADD COLUMN IF NOT EXISTS "doctorado" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "docentes" ADD COLUMN IF NOT EXISTS "cargoAdministrativo" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "docentes" ADD COLUMN IF NOT EXISTS "proyectosActivos" BOOLEAN NOT NULL DEFAULT false;
